import json

from ollama import chat

from agent.prompts import SYSTEM_PROMPT
from agent.tools import TOOLS, TOOL_MAP


MODEL = "qwen3:4b"
MAX_ITERATIONS = 5


def _serialize_tool_result(result):
    """
    Convert a tool result into JSON that can safely be sent back to Qwen.
    """
    return json.dumps(result, default=str)


def execute_tool(tool_name, arguments, customer_id=None):
    """
    Execute an agent tool while keeping customer identity under
    application control rather than letting the LLM choose it.
    """
    if tool_name not in TOOL_MAP:
        return {
            "success": False,
            "error": f"Unknown tool: {tool_name}"
        }

    tool = TOOL_MAP[tool_name]

    # These tools operate on private customer data or modify an order.
    # The authenticated customer ID comes from the application/session,
    # not from arguments generated by the LLM.
    customer_scoped_tools = {
        "lookup_order",
        "create_order",
        "cancel_order",
        "update_shipping_address",
        "request_return",
        "get_customer",
        "get_customer_orders",
    }

    if tool_name in customer_scoped_tools:
        if not customer_id:
            return {
                "success": False,
                "error": "Customer authentication is required."
            }

        # Inject the trusted customer ID here instead of allowing
        # the model to choose which customer's data to access.
        return tool(
            customer_id=customer_id,
            **arguments
        )

    return tool(**arguments)


def run_agent_turn(messages, user_input, customer_id=None):
    """
    Run one conversational turn through the tool-calling loop.

    Besides the final response, keep track of tool calls and results
    so the frontend can display the agent's process.
    """
    messages.append({
        "role": "user",
        "content": user_input
    })

    agent_steps = []
    iterations = 0

    for iteration in range(1, MAX_ITERATIONS + 1):
        iterations = iteration

        response = chat(
            model=MODEL,
            messages=messages,
            tools=TOOLS,
        )

        assistant_message = response["message"]

        messages.append(assistant_message)

        # If Qwen did not request a tool, its message is the final answer.
        if not assistant_message.get("tool_calls"):
            return {
                "response": assistant_message.get("content", ""),
                "agent_steps": agent_steps,
                "iterations": iterations,
                "completed": True,
            }

        for tool_call in assistant_message["tool_calls"]:
            function = tool_call["function"]

            tool_name = function["name"]
            arguments = function.get("arguments", {})

            # Record the tool call so the frontend can show
            # what the agent decided to use.
            agent_steps.append({
                "type": "tool_call",
                "name": tool_name,
                "arguments": arguments,
            })

            result = execute_tool(
                tool_name,
                arguments,
                customer_id=customer_id,
            )

            # Record the actual result returned by the Python tool.
            agent_steps.append({
                "type": "tool_result",
                "name": tool_name,
                "result": result,
            })

            # Send the real tool result back to Qwen so it can
            # continue reasoning with actual store data.
            messages.append({
                "role": "tool",
                "content": _serialize_tool_result(result),
            })

    return {
        "response": "I couldn't complete that request within the allowed number of steps.",
        "agent_steps": agent_steps,
        "iterations": iterations,
        "completed": False,
    }


def run_agent():
    """
    Run the agent in the terminal.
    """
    messages = [
        {
            "role": "system",
            "content": SYSTEM_PROMPT
        }
    ]

    print("D2C AI Operations Agent")
    print("Type 'exit' to quit.\n")

    while True:
        user_input = input("You: ").strip()

        if user_input.lower() == "exit":
            break

        result = run_agent_turn(
            messages,
            user_input,
        )

        print(f"Agent: {result['response']}\n")